version: '3'

networks:
  laravel:

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
  nginx:
    build:
        context: ./docker/nginx
        dockerfile: Dockerfile
    ports:
        - "80:80"
    volumes:
        - .:/var/www
    networks:
        - laravel
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  adminer:
    image: adminer
    environment: 
      ADMINER_DEFAULT_SERVER: "mysql"
    ports:
      - 8080:8080
    networks:
      - laravel